In [34]:
#this is how we will initialize the matrixes
card_wins_matrix = np.zeros((8,8))
trick_wins_matrix = np.zeros((8,8))

print(card_wins_matrix)
print(trick_wins_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
#example of filling up the matrix
i = 0
for x in range(8):
    for z in range(8):
        card_wins_matrix[x,z] = i
        trick_wins_matrix[x,z] = 64-i
        i+=1

print(card_wins_matrix)
print()
print(trick_wins_matrix)

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29. 30. 31.]
 [32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47.]
 [48. 49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62. 63.]]

[[64. 63. 62. 61. 60. 59. 58. 57.]
 [56. 55. 54. 53. 52. 51. 50. 49.]
 [48. 47. 46. 45. 44. 43. 42. 41.]
 [40. 39. 38. 37. 36. 35. 34. 33.]
 [32. 31. 30. 29. 28. 27. 26. 25.]
 [24. 23. 22. 21. 20. 19. 18. 17.]
 [16. 15. 14. 13. 12. 11. 10.  9.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.]]


In [36]:
#so this is how we are going to save the matrices
np.save("card_wins.npy",card_wins_matrix)
np.save("trick_wins.npy",trick_wins_matrix)

In [37]:
#Here is an example of loading the saved matrices so that we can
#use them again at a later time
matrix1 = np.load("card_wins.npy")
matrix2 = np.load("trick_wins.npy")