In [6]:
import seaborn as sns
import matplotlib.pyplot as plt
from  matplotlib.colors import LinearSegmentedColormap
import numpy as np
import pandas as pd

In [7]:
#Initialize dummy matrices
card_wins_matrix = np.zeros((8,8))
trick_wins_matrix = np.zeros((8,8))

#Fill dummy matrices
i = 0
for x in range(8):
    for z in range(8):
        card_wins_matrix[x,z] = i
        trick_wins_matrix[x,z] = 64-i
        i+=1

print(card_wins_matrix)
print(trick_wins_matrix)
#Save dummy matrices
np.save("card_wins.npy",card_wins_matrix)
np.save("trick_wins.npy",trick_wins_matrix)

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29. 30. 31.]
 [32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47.]
 [48. 49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62. 63.]]
[[64. 63. 62. 61. 60. 59. 58. 57.]
 [56. 55. 54. 53. 52. 51. 50. 49.]
 [48. 47. 46. 45. 44. 43. 42. 41.]
 [40. 39. 38. 37. 36. 35. 34. 33.]
 [32. 31. 30. 29. 28. 27. 26. 25.]
 [24. 23. 22. 21. 20. 19. 18. 17.]
 [16. 15. 14. 13. 12. 11. 10.  9.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.]]


In [9]:
sequences = ['BBB', 'BBR', 'BRB', 'BRR', 'RBB', 'RBR', 'RRB', 'RRR']
def create_heatmaps(card_wins = 'card_wins.npy', trick_wins = 'trick_wins.npy'):
   
    card_wins_matrix = np.load(card_wins)
    trick_wins_matrix = np.load(trick_wins)

    card_wins_df = pd.DataFrame(card_wins_matrix, index = sequences, columns = sequences)
    trick_wins_df = pd.DataFrame(trick_wins_matrix, index = sequences, columns = sequences)

    #Heatmap for number of cards
    plt.figure(figsize=(10,8))
    sns.heatmap(card_wins_df,
                annot=True,
                cmap=LinearSegmentedColormap.from_list('rg',["r", "w", "g"], N=256),
                linewidths=.5,
                cbar_kws={'label': 'Win Probability'})
    plt.title('Win Probabilities for Card Wins')
    plt.xlabel('Player 2 Choice')
    plt.ylabel('Player 1 Choice')
    plt.savefig('figures/p2_card_probs.png', bbox_inches = 'tight')

    #Heatmap for number of tricks
    plt.figure(figsize=(10,8))
    sns.heatmap(trick_wins_df,
                annot=True,
                cmap=LinearSegmentedColormap.from_list('rg',["r", "w", "g"], N=256),
                linewidths=.5,
                cbar_kws={'label': 'Win Probability'})
    plt.title('Win Probabilities for Trick Wins')
    plt.xlabel('Player 2 Choice')
    plt.ylabel('Player 1 Choice')
    plt.savefig('figures/p2_trick_probs.png', bbox_inches = 'tight')

In [ ]:
create_heatmaps()